version: "3.8"

services:
  mysqldb:
    container_name: mysqldatabase
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    networks:
      spring-mysql-net:

  springboot-restful-webservices:
      container_name: springboot-restful-webservices
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
        spring-mysql-net:
      restart: on-failure

networks:
  spring-mysql-net: